<?xml version="1.0"?>
<!DOCTYPE cateneMontuose[
<!ELEMENT cateneMontuose (catenaMontuosa*)>
<!ELEMENT catenaMontuosa (monte+)>
<!ELEMENT monte (nome,regione?,altezza?)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT regione (#PCDATA)>
<!ELEMENT altezza (#PCDATA)>
<!ATTLIST altezza unitaMisura CDATA #REQUIRED>
]>
<cateneMontuose>
  <catenaMontuosa>
    <monte>
      <nome>Mulhacen</nome>
      <regione>Granada</regione>
      <altezza unitaMisura="m">3.479</altezza>
    </monte>
    <monte>
      <nome>Teide</nome>
      <regione>Gran Canaria</regione>
      <altezza unitaMisura="m">3.718</altezza>
    </monte>
  </catenaMontuosa>
</cateneMontuose>
