<?xml version="1.0"?>
<!DOCTYPE stock[
<!ELEMENT stock (new-car | used-car)*>
<!ELEMENT new-car (model, price)>
<!ELEMENT used-car (model, price, mileage, condition?)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT mileage (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
]>
<stock>
  <new-car>
    <model>Audi Q3</model>
    <price>31.380,00 EUR</price>
  </new-car>
  <used-car>
    <model>Bmw X6</model>
    <price>39.670,00 EUR</price>
    <mileage>89.550 km</mileage>
    <condition>good</condition>
  </used-car>
</stock>
